### ISSUE TITLE
Navigation list item non interactive state

### ISSUE THREAD

**Issue by YtgmHAdHsvxfjyRYW53Y9kA9JHUKpEaKjkHs8Oy** [carbon-design-system/carbon-react-native#127] opened 2023-05-17 14:44 UTC
In the Gray 10 Theme Mobile-Carbon Design System figma file there is a component called Table Cell (Known as NavigationListItem in Carbon React Native. Design here:
https://www.figma.com/file/O3KSDu2TWpMaazGkgsKqLA/(WIP)-Gray-10-Theme-Mobile---Carbon-Design-System?node-id=12846-270703&t=6RHKVeicjb3qUDHv-4

- The Navigation list component is interactive and pressable by default but there doesn't seem to be a way to use a non interactive state (Where a user can press the Navigation list item with no active pressed down state). The w3Mobile app is using a work around at the moment by manually building a component but is there a way that this can be made configurable in the NavigationListItem component? 

![image](https://github.com/carbon-design-system/carbon-react-native/assets/139924156/b5d9ae7c-0851-44e9-82cf-8eabd700ee18)

If there is another way to render this that we are not aware of please let us know. Thank you

If you have design questions you can slack @LISA or @rjgervacio @juanencalada
If you need any additional information you can slack @kwadwo

@David-Bradshaw

**Comment by dabrad26** [comment] 2023-09-19 21:09
Closing as duplicate of #122

**Closed by dabrad26** 2023-09-19 21:09 UTC
